Disallow creating a change of a JSON file using `Change.ofText{Upsert,Patch} (#583)
Motivation:

When a change is created using `Change.ofTextUpsert()` with the following case:
1) The file type is json. e.g, `foo.json`
2) The content of `foo.json` is a plain text. e.g, `foo bar`

`Change.ofTextUpsert()` does not validate the text content and
Central Dogma raises an exception and returns 500 status.
```
com.linecorp.centraldogma.common.CentralDogmaException: unexpected response: [:status=500, content-type=application/json; charset=utf-8, server=Armeria/1.5.0, date=Tue, 6 Apr 2021 06:34:40 GMT, content-length=136], {"exception":"com.linecorp.centraldogma.server.storage.StorageException","message":"failed to convert list of DiffEntry to Changes map"}
java.util.concurrent.CompletionException: com.linecorp.centraldogma.common.CentralDogmaException: unexpected response: [:status=500, content-type=application/json; charset=utf-8, server=Armeria/1.5.0, date=Tue, 6 Apr 2021 06:34:40 GMT, content-length=136], {"exception":"com.linecorp.centraldogma.server.storage.StorageException","message":"failed to convert list of DiffEntry to Changes map"}
```

See #579 for detailed information.

Modifications:

- Raise `ChangeFormatException` when `Change.ofText{Upsert,Patch}()` is
  called with a path that ends with `.json'
  - The servers returns `400 Bad Request` to clients.

Result:

- You no longer see `500 Internal Server Error` when a text `Change` is created with a JSON file.
  Central Dogma server now returns `400 Bad Request` for the invalid input.
- Fixes #579