Fix the test failure in `CentralDogmaInitializationTimeoutTest` (#726)
Motivation:

Since `CentralDogmaInitializationTimeoutTest` uses a pre-defined port, the test is easily broken.
```
CentralDogmaInitializationTimeoutTest > initializationError FAILED
    java.util.concurrent.CompletionException: java.net.BindException: Address already in use
        at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
        at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
        at com.linecorp.armeria.common.util.EventLoopCheckingFuture.join(EventLoopCheckingFuture.java:87)
        at com.linecorp.centraldogma.client.spring.CentralDogmaInitializationTimeoutTest.beforeAll(CentralDogmaInitializationTimeoutTest.java:68)
```

Modifications:

- Retry to start the server up to 8 times with the default `Backoff`.

Result:

Hope the test doesn't fail. 🙏🙏🙏