Upgrade Java version to 17 in Dockerfile
Motivation:

The latest Central Dogma docker image failes to start up on
the `ubuntu-latest` image of GitHub Actions due to the following NPE:
```
Error: -20 09:22:41.518 [ERROR](c.l.c.s.Main) [main] Failed to start the Central Dogma:
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.linecorp.armeria.common.util.EventLoopCheckingFuture.get(EventLoopCheckingFuture.java:73)
	at com.linecorp.centraldogma.server.Main.start(Main.java:138)
	at com.linecorp.centraldogma.server.Main.main(Main.java:238)
Caused by: java.lang.NullPointerException: null
	at java.base/jdk.internal.platform.cgroupv2.CgroupV2Subsystem.getInstance(Unknown Source)
	at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(Unknown Source)
	at java.base/jdk.internal.platform.CgroupMetrics.getInstance(Unknown Source)
	at java.base/jdk.internal.platform.SystemMetrics.instance(Unknown Source)
	at java.base/jdk.internal.platform.Metrics.systemMetrics(Unknown Source)
	at java.base/jdk.internal.platform.Container.metrics(Unknown Source)
	at jdk.management/com.sun.management.internal.OperatingSystemImpl.<init>(Unknown Source)
	at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl.getOperatingSystemMXBean(Unknown Source)
	at jdk.management/com.sun.management.internal.PlatformMBeanProviderImpl$3.nameToMBeanMap(Unknown Source)
	at java.management/sun.management.spi.PlatformMBeanProvider$PlatformComponent.getMBeans(Unknown Source)
	at java.management/java.lang.management.ManagementFactory.getPlatformMXBean(Unknown Source)
	at java.management/java.lang.management.ManagementFactory.getOperatingSystemMXBean(Unknown Source)
	at io.micrometer.core.instrument.binder.system.FileDescriptorMetrics.<init>(FileDescriptorMetrics.java:78)
	at io.micrometer.core.instrument.binder.system.FileDescriptorMetrics.<init>(FileDescriptorMetrics.java:74)
	at com.linecorp.centraldogma.server.CentralDogma.configureMetrics(CentralDogma.java:1130)
	at com.linecorp.centraldogma.server.CentralDogma.startServer(CentralDogma.java:772)
	at com.linecorp.centraldogma.server.CentralDogma.doStart(CentralDogma.java:474)
	at com.linecorp.centraldogma.server.CentralDogma.access$800(CentralDogma.java:198)
	at com.linecorp.centraldogma.server.CentralDogma$CentralDogmaStartStop.lambda$doStart$0(CentralDogma.java:1306)
	at com.linecorp.centraldogma.server.CentralDogma$CentralDogmaStartStop.lambda$execute$2(CentralDogma.java:1345)
	at java.base/java.lang.Thread.run(Unknown Source)
```
The exception seems fixed by https://bugs.openjdk.org/browse/JDK-8287073

Related: https://github.com/line/centraldogma-python/pull/70

Modifications:

- Upgrade the JRE version of the Docker image to 17
- Add a CI test to check if Central Dogma Docker image starts successfully

Result:

Central Dogma Docker image now starts up propertly in GitHub Actions.