Make a server unhealth when it is about to shut down.
Motivation:

If a server stops, it closes the internal resources first and finally
stops Armeria server. As there is no custom `HealthChecker` specified,
the status of the server becomes unhealthy when Armeria server start to
shut down. Meanwhile, clients try to send new requests to the closing
server.

I also found that a `CompletionException` is not properly peeled when
an `HttpResponse` is created by `HttpApiUtil`.
```
com.linecorp.centraldogma.common.CentralDogmaException: unexpected response: [:status=500, content-type=application/json; charset=utf-8, ...]
   {"exception":"java.util.concurrent.CompletionException","message":"com.linecorp.centraldogma.common.ShuttingDownException"}
	at com.linecorp.centraldogma.client.armeria.ArmeriaCentralDogma.handleErrorResponse(ArmeriaCentralDogma.java:1135)
	at com.linecorp.centraldogma.client.armeria.ArmeriaCentralDogma.normalizeRevision(ArmeriaCentralDogma.java:396)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
```

Modifications:

- Add a `SettableHealthChecker` which becomes healthy when a Armeria
  server is completely started and becomes unhealthy when a Central
  Dogma server is about to close.
- Peel a exception before it is converted to an `HttpResponse` in `HttpApiUtil`.

Result:

You will no longer see `ShuttingDownException` warning messages.