Fix a bug where markdown files fail to render in the diff view.
Motivation:

Prism raises an exception if a markdown file is specified in the commit
diff view. Because the markdown syntax is not imported from
`'prismjs/components/*`.

```
framework-0e8d27528ba61906.js:9 Error: The language "markdown" has no grammar.
    at Object.highlight (1809-d263923ea021c688.js:8:3755)
    at [[...path]]-3633ecc2aa697c21.js:1:2753
    at Object.renderContent ([[...path]]-3633ecc2aa697c21.js:1:2844)
    ...
```

Modifications:

- Support more widely used languages by declaring `prismjs/components/<lang>`
- Fall back to the plantext mode if `Prism` raises an exception.
- Minor) Move Java files for test servers to `webapp/javaTest` for easier
  discovery.

Result:

Markdown files are now correctly rendered in the diff view.