Respond '204 No Content' when attempting to get no content. (#442)
Motivation:

A `503 Internal Server Error` is returned when attempting to get directory content:

    Returning an internal server error: DIRECTORY does not have content
    java.lang.IllegalStateException: DIRECTORY does not have content
     at com.linecorp.centraldogma.common.Entry.content(Entry.java:174)
     at com.linecorp.centraldogma.common.ContentHolder.contentAsText(ContentHolder.java:52)
     at com.linecorp.centraldogma.common.Entry.contentAsText(Entry.java:182)
     at com.linecorp.centraldogma.server.internal.admin.service.DtoConverter.convert(DtoConverter.java:96)

Modifications:
- Added `EntryNoContentException`.
- If the content of the entry is `null`, an `EntryNoContentException` is thrown.
- If occur `EntryNoContentException`, respond `204 No-Content` Response with `No-Body`.

Result:
- Fixes #414
- If the content of the entry is `null`,  return a `204 No-Content` Response.